### ISSUE TITLE
RF13 - El sistema debe mostrar claramente si el vendedor esta activo o no

### ISSUE THREAD

**Issue by druzmieres** [DCC-CC4401/Los-Gremlins#14]
Ficha de vendedor (vista por un alumno).

**Comment by Vichoko** [comment]
Los vendedores ambulantes tienen un camo 'is_active' que se debe ir actualizando.
Para los fijos, se calcula mediante una función.

**Comment by Vichoko** [comment]
Solo falta el tema del vendedor fijo
