### ISSUE TITLE
RF14 - El sistema debe mostrar las formas de pago aceptadas por el vendedor

### ISSUE THREAD

**Issue by druzmieres** [DCC-CC4401/Los-Gremlins#15]
Ficha de vendedor (vista por un alumno).

**Comment by Vichoko** [comment]
Si bien están en la base de datos correctamente, no se estan mostrando en la ficha.

**Comment by Vichoko** [comment]
Por algun motivo no se pueden sacar de labase de datos como estan guardads ahora.
