### ISSUE TITLE
RF21 - El sistema debe permitir gestionar las formas de pago aceptadas por el vendedor

### ISSUE THREAD

**Issue by druzmieres** [DCC-CC4401/Los-Gremlins#22]
Ficha de vendedor (vista por un vendedor).

**Comment by Vichoko** [comment]
Está funcionando por detrás, solo que no se están mostrando aun en ficha de vendedor.
Apenas arreglemos visualizacion CT:

**Comment by Vichoko** [comment]
se peude hacer mediante la edicion del perfild e vendedor.
