### ISSUE TITLE
RF22 - El sistema debe mostrar cuántos usuarios lo han seleccionado como “favorito”

### ISSUE THREAD

**Issue by druzmieres** [DCC-CC4401/Los-Gremlins#23]
Ficha de vendedor (vista por un vendedor).

**Comment by Vichoko** [comment]
Pensé que la forma trivial de hacerlo es mediante un campo en el vendedor que diga cuantas veces ha sido elegido favorito. Este campo fue agregado ya en la branch 'ficha-vendedor', se espera subir pronto a develop.
