### ISSUE TITLE
RF23 - El sistema debe mostrar la información para un producto

### ISSUE THREAD

**Issue by druzmieres** [DCC-CC4401/Los-Gremlins#24]
El sistema debe mostrar nombre, foto, categoría, descripción, stock, precio.

Ficha de producto.

**Comment by PabloReszczynski** [comment]
Que informacion debe aparecer cuando uno entra como usuario y no como el vendedor duenno del producto?

**Comment by druzmieres** [comment]
Debe aparecer lo mismo que sale más arriba, pero sin la posibilidad de editar.

**Comment by Vichoko** [comment]
No me queda claro si debe haber una pagina solo para esto, o se ven solo desde la ficha del vendedor:
[http://prntscr.com/fd6xz5](url)
