### ISSUE TITLE
RF24 - En el caso de los vendedores, el sistema debe permitir gestionar la información de un producto

### ISSUE THREAD

**Issue by druzmieres** [DCC-CC4401/Los-Gremlins#25]
Ficha de producto.

**Comment by Vichoko** [comment]
Modificar la ficha de producto se puede lograr con django forms: https://docs.djangoproject.com/en/1.11/topics/forms/#building-a-form-in-django

**Comment by druzmieres** [comment]
El sistema debe mostrar nombre, foto, categoría, descripción, stock, precio.

**Comment by Vichoko** [comment]
Creo que esta implementado, falta probarlo.
