### ISSUE TITLE
RF26 - El sistema debe permitir la gestión (creación, modificación y eliminación) de usuarios

### ISSUE THREAD

**Issue by druzmieres** [DCC-CC4401/Los-Gremlins#29]
Interfaces de administración (solo para usuarios de tipo administrador).

**Comment by PabloReszczynski** [comment]
Esto deberia poder hacerse de la misma página de /admin

**Comment by Vichoko** [comment]
Encotnre dificil hacerlo con la pagina de admin asi que le dare poder a los admin de poder editar con la edit form y una forma de elimnar cuentas.

**Comment by Vichoko** [comment]
admin tiene poder para editar cuaqluier ficha. Ademas pueden borrar usuarios mediante una url.
