### ISSUE TITLE
Debe existir el modelo de usuarios.

### ISSUE THREAD

**Issue by PabloReszczynski** [DCC-CC4401/Los-Gremlins#32]
Tantos usuarios como vendedores deben tener un modelo en la base de datos. Discutir aquí cómo se hará.
ie: Columnas, relaciones, etc.

Realizar este requerimiento es necesario para implementar los issues #2 y  #33

**Comment by Vichoko** [comment]
Los modelos de usuario estan en ```user.models.py```, se implementaron a lo django database.
La idea sería implementaría aqui los modelos de usuario, admin, vendedor ambulante y fijo, y alumno. 

Despues desde otras apps se importan con ```from user import models``` y se pueden sacar de la base de datos y ble.

**Comment by Vichoko** [comment]
Todos los modelos de usuarios están en lo que dije arriba.
